#!/bin/bash -e

command_exists () {
  type "$1" &> /dev/null ;
}

get_oai_id () {
  OAI=$1
  echo "$OAI" |
  grep '"Id"' |
  sed -E 's/"Id": "(.*)",/\1/' |
  tr -d ' '
}

if ! command_exists aws; then
  echo "You need aws-cli to run this!"
  echo "For instructions on how to install it, see:"
  echo "https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-set-up.html"
  exit 1
fi

ROOT_DOMAIN_NAME=$1
STACK_NAME=$(echo $ROOT_DOMAIN_NAME | sed -E 's/[^a-zA-Z0-9\-]+/-/g')

echo "Start provisioning ${ROOT_DOMAIN_NAME}"

echo "Provisioning Cloudfront Origin Access Identity"
OAI_COMMENT="${STACK_NAME}-cloudfront-identity"

OAI_CONFIG="CallerReference=${STACK_NAME}-identity,Comment=${OAI_COMMENT}"
OAI=$(aws cloudfront create-cloud-front-origin-access-identity --cloud-front-origin-access-identity-config ${OAI_CONFIG})

OAI_ID="$(get_oai_id "${OAI}")"
OAI_LOCATION="origin-access-identity/cloudfront/${OAI_ID}"

echo "Deploying Cloudformation stack ${STACK_NAME} for ${ROOT_DOMAIN_NAME}"
aws cloudformation deploy --stack-name "${STACK_NAME}" --template-file cloudformation/template.yml --parameter-overrides "RootDomainName=${ROOT_DOMAIN_NAME}" "OriginAccessIdentity=${OAI_LOCATION}"

echo "Stack provisioned successfully!"

echo "Describing Stack"
aws cloudformation describe-stacks --stack-name "${STACK_NAME}"
